# Generated by Django 6.0 on 2025-12-20 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'object_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'prog',
                'ordering': ['prog_name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'region',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'work_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PdfStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('sha256', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pdf_storage',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='arxiv.region')),
            ],
            options={
                'db_table': 'district',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Arxiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_num', models.CharField(max_length=100, unique=True)),
                ('reg_date', models.DateField()),
                ('customer', models.CharField(max_length=255)),
                ('object_name', models.CharField(max_length=255)),
                ('signed_person', models.CharField(max_length=255)),
                ('branch_manager', models.CharField(max_length=255)),
                ('specialist', models.CharField(max_length=255)),
                ('is_mutch', models.BooleanField(default=False)),
                ('book_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arxiv_items', to='arxiv.district')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arxiv_items', to='arxiv.objecttype')),
                ('pdf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arxiv_items', to='arxiv.pdfstorage')),
                ('prog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arxiv_items', to='arxiv.prog')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arxiv_items', to='arxiv.region')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arxiv_items', to='arxiv.worktype')),
            ],
            options={
                'db_table': 'arxiv',
                'ordering': ['-reg_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['region', 'name'], name='district_region__5baebe_idx'),
        ),
        migrations.AddIndex(
            model_name='arxiv',
            index=models.Index(fields=['reg_num'], name='arxiv_reg_num_3f1176_idx'),
        ),
        migrations.AddIndex(
            model_name='arxiv',
            index=models.Index(fields=['reg_date'], name='arxiv_reg_dat_db2554_idx'),
        ),
        migrations.AddIndex(
            model_name='arxiv',
            index=models.Index(fields=['customer'], name='arxiv_custome_80c4e9_idx'),
        ),
        migrations.AddIndex(
            model_name='arxiv',
            index=models.Index(fields=['region', 'district'], name='arxiv_region__bb7782_idx'),
        ),
    ]
