# Generated by Django 6.0 on 2025-12-22 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arxiv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='worktype',
            options={},
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='book_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Kitob raqami'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='branch_manager',
            field=models.CharField(max_length=255, verbose_name='Filial rahbari'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='customer',
            field=models.CharField(max_length=255, verbose_name='Buyurtmachi'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arxiv_items', to='arxiv.district', verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='is_mutch',
            field=models.BooleanField(default=False, verbose_name='Muvofiq'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='object_name',
            field=models.CharField(max_length=255, verbose_name='Ob`yekt nomi'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arxiv_items', to='arxiv.objecttype', verbose_name='Obyekt turi'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='prog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arxiv_items', to='arxiv.prog', verbose_name='Dastur nomi'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='reg_date',
            field=models.DateField(verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='reg_num',
            field=models.CharField(max_length=100, unique=True, verbose_name='Ro`yxatga olingan raqami'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arxiv_items', to='arxiv.region', verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='signed_person',
            field=models.CharField(max_length=255, verbose_name='Bayonnomani imzolagan shaxs'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='specialist',
            field=models.CharField(max_length=255, verbose_name='Sinov o`tkazgan mutaxassis'),
        ),
        migrations.AlterField(
            model_name='arxiv',
            name='work_type',
            field=models.CharField(max_length=255, verbose_name='Ish turi'),
        ),
        migrations.AlterModelTable(
            name='worktype',
            table=None,
        ),
    ]
